CMFD: cmfd_input Module Reference
cmfd_input Module Reference
Functions/Subroutines
subroutine, public read_input ()
integer get_matrix_idx (g, i, j, k, ng, nx, ny)
Function/Subroutine Documentation
integer cmfd_input::get_matrix_idx (integer g, integer i, integer j, integer k, integer ng, integer nx, integer ny)
Definition at line 287 of file cmfd_input.F90.
Referenced by read_input().
subroutine,public cmfd_input::read_input ()
Definition at line 13 of file cmfd_input.F90.
References global::cmfd, xml_data_cmfd_t::geometry, get_matrix_idx(), xml_data_cmfd_t::mat, and xml_data_cmfd_t::read_xml_file_cmfd_t().
Referenced by cmfd_data::set_up_cmfd().