CMFD: global Module Reference
global Module Reference
Variables
type(cmfd_obj) cmfd
type(Timer) time_total
type(Timer) time_mat
type(Timer) time_power
integer ierr
logical master = .false.
integer rank
integer n_procs
character(len=25) solver_type
Variable Documentation
type(cmfd_obj) global::cmfd
Definition at line 10 of file global.F90.
Referenced by cmfd_loss_operator::build_loss_matrix(), cmfd_prod_operator::build_prod_matrix(), cmfd_power_solver::cmfd_power_execute(), cmfd_data::compute_dtilde(), cmfd_snes_solver::extract_results(), cmfd_slepc_solver::extract_results(), finalize(), cmfd_output::get_matrix_idx(), cmfd_snes_solver::init_data(), cmfd_prod_operator::init_F_operator(), cmfd_jacobian_operator::init_J_operator(), cmfd_loss_operator::init_M_operator(), cmfd_output::neutron_balance(), cmfd_input::read_input(), and cmfd_output::write_cmfd_vtk().
integer global::ierr
Definition at line 18 of file global.F90.
Referenced by finalize(), and initialize().
logical global::master = .false.
Definition at line 21 of file global.F90.
Referenced by finalize(), and initialize().
integer global::n_procs
Definition at line 23 of file global.F90.
Referenced by cmfd_jacobian_operator::build_jacobian_matrix(), cmfd_snes_solver::compute_nonlinear_residual(), cmfd_snes_solver::extract_results(), cmfd_snes_solver::init_data(), initialize(), and cmfd_jacobian_operator::preallocate_jacobian_matrix().
integer global::rank
Definition at line 22 of file global.F90.
Referenced by cmfd_jacobian_operator::build_jacobian_matrix(), cmfd_snes_solver::compute_nonlinear_residual(), cmfd_snes_solver::extract_results(), cmfd_snes_solver::init_data(), initialize(), and cmfd_jacobian_operator::preallocate_jacobian_matrix().
character(len=25) global::solver_type
Definition at line 26 of file global.F90.
Referenced by cmfd_execute::execute_cmfd(), and initialize().
type(Timer) global::time_mat
Definition at line 14 of file global.F90.
type(Timer) global::time_power
Definition at line 15 of file global.F90.
type(Timer) global::time_total
Definition at line 13 of file global.F90.
Referenced by finalize(), and main().