CMFD: timing Module Reference
timing Module Reference
Data Types
type Timer
Functions/Subroutines
subroutine timer_start (self)
real(8) timer_get_value (self)
subroutine timer_stop (self)
subroutine timer_reset (self)
Function/Subroutine Documentation
real(8) timing::timer_get_value (type(Timer),intent(in) self)
Definition at line 44 of file timing.F90.
Referenced by timer_stop().
subroutine timing::timer_reset (type(Timer),intent(inout) self)
Definition at line 84 of file timing.F90.
References constants::ZERO.
subroutine timing::timer_start (type(Timer),intent(inout) self)
Definition at line 30 of file timing.F90.
Referenced by main().
subroutine timing::timer_stop (type(Timer),intent(inout) self)
Definition at line 67 of file timing.F90.
References timer_get_value().
Referenced by main().