CMFD: cmfd_snes_solver Module Reference
cmfd_snes_solver Module Reference
Functions/Subroutines
subroutine cmfd_snes_execute ()
subroutine init_data ()
subroutine init_solver ()
subroutine compute_nonlinear_residual (snes, x, res, ierr)
subroutine extract_results ()
subroutine finalize ()
Variables
type(jacobian_operator) jac_prec
type(operators) ctx
integer ierr
Function/Subroutine Documentation
subroutine cmfd_snes_solver::cmfd_snes_execute ()
Definition at line 34 of file cmfd_snes_solver.F90.
References cmfd_slepc_solver::cmfd_slepc_execute(), extract_results(), finalize(), ierr, init_data(), and init_solver().
Referenced by cmfd_execute::execute_cmfd().
subroutine cmfd_snes_solver::compute_nonlinear_residual (snes , x , res , integer ierr)
Definition at line 167 of file cmfd_snes_solver.F90.
References ctx, global::n_procs, and global::rank.
Referenced by init_solver().
subroutine cmfd_snes_solver::extract_results ()
Definition at line 256 of file cmfd_snes_solver.F90.
References global::cmfd, ctx, ierr, global::n_procs, and global::rank.
Referenced by cmfd_snes_execute().
subroutine cmfd_snes_solver::finalize ()
Definition at line 302 of file cmfd_snes_solver.F90.
References ctx, ierr, and jac_prec.
Referenced by cmfd_snes_execute().
subroutine cmfd_snes_solver::init_data ()
Definition at line 60 of file cmfd_snes_solver.F90.
References global::cmfd, ctx, ierr, cmfd_prod_operator::init_F_operator(), cmfd_jacobian_operator::init_J_operator(), cmfd_loss_operator::init_M_operator(), jac_prec, global::n_procs, and global::rank.
Referenced by cmfd_snes_execute().
subroutine cmfd_snes_solver::init_solver ()
Definition at line 107 of file cmfd_snes_solver.F90.
References compute_nonlinear_residual(), ctx, ierr, and jac_prec.
Referenced by cmfd_snes_execute().
Variable Documentation
type(operators) cmfd_snes_solver::ctx
Definition at line 17 of file cmfd_snes_solver.F90.
Referenced by compute_nonlinear_residual(), extract_results(), finalize(), init_data(), and init_solver().
integer cmfd_snes_solver::ierr
Definition at line 26 of file cmfd_snes_solver.F90.
Referenced by cmfd_snes_execute(), extract_results(), finalize(), init_data(), and init_solver().
type(jacobian_operator) cmfd_snes_solver::jac_prec
Definition at line 16 of file cmfd_snes_solver.F90.
Referenced by finalize(), init_data(), and init_solver().