CMFD: cmfd_data Module Reference
cmfd_data Module Reference
Functions/Subroutines
subroutine, public set_up_cmfd ()
subroutine compute_dtilde ()
Function/Subroutine Documentation
subroutine cmfd_data::compute_dtilde ()
Definition at line 29 of file cmfd_data.F90.
References global::cmfd.
Referenced by set_up_cmfd().
subroutine,public cmfd_data::set_up_cmfd ()
Definition at line 13 of file cmfd_data.F90.
References compute_dtilde(), and cmfd_input::read_input().
Referenced by cmfd_execute::execute_cmfd().