CMFD: cmfd_power_solver Module Reference
cmfd_power_solver Module Reference
Functions/Subroutines
subroutine, public cmfd_power_execute ()
subroutine finalize ()
Variables
type(loss_operator) loss
type(prod_operator) prod
integer ierr
real(8) k_n
real(8) k_o
logical iconv
Function/Subroutine Documentation
subroutine,public cmfd_power_solver::cmfd_power_execute ()
Definition at line 34 of file cmfd_power_solver.F90.
References global::cmfd, finalize(), iconv, ierr, cmfd_prod_operator::init_F_operator(), cmfd_loss_operator::init_M_operator(), k_n, k_o, loss, and prod.
Referenced by cmfd_execute::execute_cmfd().
subroutine cmfd_power_solver::finalize ()
Definition at line 261 of file cmfd_power_solver.F90.
References ierr, loss, and prod.
Referenced by cmfd_power_execute().
Variable Documentation
logical cmfd_power_solver::iconv
Definition at line 26 of file cmfd_power_solver.F90.
Referenced by cmfd_power_execute().
integer cmfd_power_solver::ierr
Definition at line 23 of file cmfd_power_solver.F90.
Referenced by cmfd_power_execute(), and finalize().
real(8) cmfd_power_solver::k_n
Definition at line 24 of file cmfd_power_solver.F90.
Referenced by cmfd_power_execute().
real(8) cmfd_power_solver::k_o
Definition at line 25 of file cmfd_power_solver.F90.
Referenced by cmfd_power_execute().
type(loss_operator) cmfd_power_solver::loss
Definition at line 14 of file cmfd_power_solver.F90.
Referenced by cmfd_power_execute(), and finalize().
type(prod_operator) cmfd_power_solver::prod
Definition at line 15 of file cmfd_power_solver.F90.
Referenced by cmfd_power_execute(), and finalize().