CMFD: cmfd_loss_operator Module Reference
cmfd_loss_operator Module Reference
Data Types
type loss_operator
Functions/Subroutines
subroutine, public init_M_operator (this)
subroutine preallocate_loss_matrix (this)
subroutine, public build_loss_matrix (this)
subroutine indices_to_matrix (g, i, j, k, matidx)
subroutine matrix_to_indices (irow, g, i, j, k)
subroutine print_M_operator (this)
subroutine, public destroy_M_operator (this)
Variables
integer nx
integer ny
integer nz
integer ng
integer ierr
Function/Subroutine Documentation
subroutine,public cmfd_loss_operator::build_loss_matrix (type(loss_operator) this)
Definition at line 214 of file cmfd_loss_operator.F90.
References global::cmfd, ierr, indices_to_matrix(), matrix_to_indices(), ng, nx, ny, nz, and print_M_operator().
subroutine,public cmfd_loss_operator::destroy_M_operator (type(loss_operator) this)
Definition at line 421 of file cmfd_loss_operator.F90.
References ierr.
subroutine cmfd_loss_operator::indices_to_matrix (integer g, integer i, integer j, integer k, integer matidx)
Definition at line 362 of file cmfd_loss_operator.F90.
References ng, nx, and ny.
Referenced by build_loss_matrix(), and preallocate_loss_matrix().
subroutine,public cmfd_loss_operator::init_M_operator (type(loss_operator) this)
Definition at line 32 of file cmfd_loss_operator.F90.
References global::cmfd, ierr, ng, nx, ny, nz, and preallocate_loss_matrix().
Referenced by cmfd_power_solver::cmfd_power_execute(), cmfd_snes_solver::init_data(), and cmfd_slepc_solver::init_data().
subroutine cmfd_loss_operator::matrix_to_indices (integer irow, integer g, integer i, integer j, integer k)
Definition at line 381 of file cmfd_loss_operator.F90.
References ng, nx, ny, and nz.
Referenced by build_loss_matrix(), and preallocate_loss_matrix().
subroutine cmfd_loss_operator::preallocate_loss_matrix (type(loss_operator) this)
Definition at line 79 of file cmfd_loss_operator.F90.
References ierr, indices_to_matrix(), matrix_to_indices(), ng, nx, ny, and nz.
Referenced by init_M_operator().
subroutine cmfd_loss_operator::print_M_operator (type(loss_operator) this)
Definition at line 403 of file cmfd_loss_operator.F90.
References ierr.
Referenced by build_loss_matrix().
Variable Documentation
integer cmfd_loss_operator::ierr
Definition at line 13 of file cmfd_loss_operator.F90.
Referenced by build_loss_matrix(), destroy_M_operator(), init_M_operator(), preallocate_loss_matrix(), and print_M_operator().
integer cmfd_loss_operator::ng
Definition at line 12 of file cmfd_loss_operator.F90.
Referenced by build_loss_matrix(), indices_to_matrix(), init_M_operator(), matrix_to_indices(), and preallocate_loss_matrix().
integer cmfd_loss_operator::nx
Definition at line 9 of file cmfd_loss_operator.F90.
Referenced by build_loss_matrix(), indices_to_matrix(), init_M_operator(), matrix_to_indices(), and preallocate_loss_matrix().
integer cmfd_loss_operator::ny
Definition at line 10 of file cmfd_loss_operator.F90.
Referenced by build_loss_matrix(), indices_to_matrix(), init_M_operator(), matrix_to_indices(), and preallocate_loss_matrix().
integer cmfd_loss_operator::nz
Definition at line 11 of file cmfd_loss_operator.F90.
Referenced by build_loss_matrix(), init_M_operator(), matrix_to_indices(), and preallocate_loss_matrix().