CMFD: cmfd_prod_operator Module Reference
cmfd_prod_operator Module Reference
Data Types
type prod_operator
Functions/Subroutines
subroutine, public init_F_operator (this)
subroutine preallocate_prod_matrix (this)
subroutine, public build_prod_matrix (this)
subroutine indices_to_matrix (g, i, j, k, matidx)
subroutine matrix_to_indices (irow, g, i, j, k)
subroutine print_F_operator (this)
subroutine, public destroy_F_operator (this)
Variables
integer nx
integer ny
integer nz
integer ng
integer ierr
Function/Subroutine Documentation
subroutine,public cmfd_prod_operator::build_prod_matrix (type(prod_operator) this)
Definition at line 167 of file cmfd_prod_operator.F90.
References global::cmfd, indices_to_matrix(), matrix_to_indices(), ng, and print_F_operator().
subroutine,public cmfd_prod_operator::destroy_F_operator (type(prod_operator) this)
Definition at line 286 of file cmfd_prod_operator.F90.
References ierr.
subroutine cmfd_prod_operator::indices_to_matrix (integer g, integer i, integer j, integer k, integer matidx)
Definition at line 227 of file cmfd_prod_operator.F90.
References ng, nx, and ny.
Referenced by build_prod_matrix(), and preallocate_prod_matrix().
subroutine,public cmfd_prod_operator::init_F_operator (type(prod_operator) this)
Definition at line 32 of file cmfd_prod_operator.F90.
References global::cmfd, ierr, ng, nx, ny, nz, and preallocate_prod_matrix().
Referenced by cmfd_power_solver::cmfd_power_execute(), cmfd_snes_solver::init_data(), and cmfd_slepc_solver::init_data().
subroutine cmfd_prod_operator::matrix_to_indices (integer irow, integer g, integer i, integer j, integer k)
Definition at line 246 of file cmfd_prod_operator.F90.
References ng, nx, ny, and nz.
Referenced by build_prod_matrix(), and preallocate_prod_matrix().
subroutine cmfd_prod_operator::preallocate_prod_matrix (type(prod_operator) this)
Definition at line 79 of file cmfd_prod_operator.F90.
References ierr, indices_to_matrix(), matrix_to_indices(), and ng.
Referenced by init_F_operator().
subroutine cmfd_prod_operator::print_F_operator (type(prod_operator) this)
Definition at line 268 of file cmfd_prod_operator.F90.
References ierr.
Referenced by build_prod_matrix().
Variable Documentation
integer cmfd_prod_operator::ierr
Definition at line 13 of file cmfd_prod_operator.F90.
Referenced by destroy_F_operator(), init_F_operator(), preallocate_prod_matrix(), and print_F_operator().
integer cmfd_prod_operator::ng
Definition at line 12 of file cmfd_prod_operator.F90.
Referenced by build_prod_matrix(), indices_to_matrix(), init_F_operator(), matrix_to_indices(), and preallocate_prod_matrix().
integer cmfd_prod_operator::nx
Definition at line 9 of file cmfd_prod_operator.F90.
Referenced by indices_to_matrix(), init_F_operator(), and matrix_to_indices().
integer cmfd_prod_operator::ny
Definition at line 10 of file cmfd_prod_operator.F90.
Referenced by indices_to_matrix(), init_F_operator(), and matrix_to_indices().
integer cmfd_prod_operator::nz
Definition at line 11 of file cmfd_prod_operator.F90.
Referenced by init_F_operator(), and matrix_to_indices().