CMFD: xml_data_cmfd_t Module Reference
xml_data_cmfd_t Module Reference
Data Types
type geometry_xml
type mat_xml
Functions/Subroutines
subroutine read_xml_type_geometry_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_geometry_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_geometry_xml_array (dvar)
subroutine init_xml_type_geometry_xml (dvar)
subroutine write_xml_type_geometry_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_geometry_xml (info, tag, indent, dvar)
subroutine read_xml_type_mat_xml_array (info, tag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine read_xml_type_mat_xml (info, starttag, endtag, attribs, noattribs, data, nodata, dvar, has_dvar)
subroutine init_xml_type_mat_xml_array (dvar)
subroutine init_xml_type_mat_xml (dvar)
subroutine write_xml_type_mat_xml_array (info, tag, indent, dvar)
subroutine write_xml_type_mat_xml (info, tag, indent, dvar)
subroutine read_xml_file_cmfd_t (fname, lurep, errout)
subroutine write_xml_file_cmfd_t (fname, lurep)
subroutine init_xml_file_cmfd_t
Variables
integer, private lurep_
logical, private strict_
type(geometry_xml) geometry
type(mat_xml), dimension(:),
pointer mat = > null()
Function/Subroutine Documentation
subroutine xml_data_cmfd_t::init_xml_file_cmfd_t ()
Definition at line 648 of file xml_cmfd.F90.
Referenced by read_xml_file_cmfd_t().
subroutine xml_data_cmfd_t::init_xml_type_geometry_xml (type(geometry_xml) dvar)
Definition at line 278 of file xml_cmfd.F90.
Referenced by read_xml_type_geometry_xml().
subroutine xml_data_cmfd_t::init_xml_type_geometry_xml_array (type(geometry_xml),dimension(:),pointer dvar)
Definition at line 271 of file xml_cmfd.F90.
subroutine xml_data_cmfd_t::init_xml_type_mat_xml (type(mat_xml) dvar)
Definition at line 501 of file xml_cmfd.F90.
Referenced by read_xml_type_mat_xml().
subroutine xml_data_cmfd_t::init_xml_type_mat_xml_array (type(mat_xml),dimension(:),pointer dvar)
Definition at line 494 of file xml_cmfd.F90.
subroutine xml_data_cmfd_t::read_xml_file_cmfd_t (character(len=*),intent(in) fname, integer,intent(in),optional lurep, logical,intent(out),optional errout)
Definition at line 537 of file xml_cmfd.F90.
References geometry, init_xml_file_cmfd_t(), lurep_, mat, read_xml_type_geometry_xml(), read_xml_type_mat_xml_array(), and strict_.
Referenced by cmfd_input::read_input().
subroutine xml_data_cmfd_t::read_xml_type_geometry_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(geometry_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 63 of file xml_cmfd.F90.
References init_xml_type_geometry_xml(), lurep_, and strict_.
Referenced by read_xml_file_cmfd_t(), and read_xml_type_geometry_xml_array().
subroutine xml_data_cmfd_t::read_xml_type_geometry_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(geometry_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 37 of file xml_cmfd.F90.
References read_xml_type_geometry_xml().
subroutine xml_data_cmfd_t::read_xml_type_mat_xml (type(XML_PARSE) info, character(len=*),intent(in) starttag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(mat_xml),intent(inout) dvar, logical,intent(inout) has_dvar)
Definition at line 346 of file xml_cmfd.F90.
References init_xml_type_mat_xml(), lurep_, and strict_.
Referenced by read_xml_type_mat_xml_array().
subroutine xml_data_cmfd_t::read_xml_type_mat_xml_array (type(XML_PARSE) info, character(len=*),intent(inout) tag, logical,intent(inout) endtag, character(len=*),dimension(:,:),intent(inout) attribs, integer,intent(inout) noattribs, character(len=*),dimension(:),intent(inout) data, integer,intent(inout) nodata, type(mat_xml),dimension(:),pointer dvar, logical,intent(inout) has_dvar)
Definition at line 320 of file xml_cmfd.F90.
References read_xml_type_mat_xml().
Referenced by read_xml_file_cmfd_t().
subroutine xml_data_cmfd_t::write_xml_file_cmfd_t (character(len=*),intent(in) fname, integer,intent(in),optional lurep)
Definition at line 628 of file xml_cmfd.F90.
References geometry, mat, write_xml_type_geometry_xml(), and write_xml_type_mat_xml_array().
subroutine xml_data_cmfd_t::write_xml_type_geometry_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(geometry_xml) dvar)
Definition at line 293 of file xml_cmfd.F90.
Referenced by write_xml_file_cmfd_t(), and write_xml_type_geometry_xml_array().
subroutine xml_data_cmfd_t::write_xml_type_geometry_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(geometry_xml),dimension(:) dvar)
Definition at line 281 of file xml_cmfd.F90.
References write_xml_type_geometry_xml().
subroutine xml_data_cmfd_t::write_xml_type_mat_xml (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(mat_xml) dvar)
Definition at line 516 of file xml_cmfd.F90.
Referenced by write_xml_type_mat_xml_array().
subroutine xml_data_cmfd_t::write_xml_type_mat_xml_array (type(XML_PARSE) info, character(len=*),intent(in) tag, integer indent, type(mat_xml),dimension(:) dvar)
Definition at line 504 of file xml_cmfd.F90.
References write_xml_type_mat_xml().
Referenced by write_xml_file_cmfd_t().
Variable Documentation
type(geometry_xml) xml_data_cmfd_t::geometry
Definition at line 34 of file xml_cmfd.F90.
Referenced by cmfd_input::read_input(), read_xml_file_cmfd_t(), and write_xml_file_cmfd_t().
integer,private xml_data_cmfd_t::lurep_
Definition at line 6 of file xml_cmfd.F90.
Referenced by read_xml_file_cmfd_t(), read_xml_type_geometry_xml(), and read_xml_type_mat_xml().
type(mat_xml),dimension(:),pointer xml_data_cmfd_t::mat = > null()
Definition at line 35 of file xml_cmfd.F90.
Referenced by cmfd_input::read_input(), read_xml_file_cmfd_t(), and write_xml_file_cmfd_t().
logical,private xml_data_cmfd_t::strict_
Definition at line 7 of file xml_cmfd.F90.
Referenced by read_xml_file_cmfd_t(), read_xml_type_geometry_xml(), and read_xml_type_mat_xml().