CMFD: cmfd_jacobian_operator Module Reference
cmfd_jacobian_operator Module Reference
Data Types
type jacobian_operator
type operators
Functions/Subroutines
subroutine, public init_J_operator (this, ctx)
subroutine preallocate_jacobian_matrix (this, ctx)
subroutine, public build_jacobian_matrix (snes, x, jac, jac_prec, flag, ctx, ierr)
subroutine print_J_operator (jac)
subroutine, public destroy_J_operator (this)
Variables
integer nx
integer ny
integer nz
integer ng
integer ierr
Function/Subroutine Documentation
subroutine,public cmfd_jacobian_operator::build_jacobian_matrix (snes , x , jac , jac_prec , flag , type(operators) ctx, integer ierr)
Definition at line 177 of file cmfd_jacobian_operator.F90.
References global::n_procs, print_J_operator(), and global::rank.
subroutine,public cmfd_jacobian_operator::destroy_J_operator (type(jacobian_operator) this)
Definition at line 345 of file cmfd_jacobian_operator.F90.
References ierr.
subroutine,public cmfd_jacobian_operator::init_J_operator (type(jacobian_operator) this, type(operators) ctx)
Definition at line 42 of file cmfd_jacobian_operator.F90.
References global::cmfd, ierr, ng, nx, ny, nz, and preallocate_jacobian_matrix().
Referenced by cmfd_snes_solver::init_data().
subroutine cmfd_jacobian_operator::preallocate_jacobian_matrix (type(jacobian_operator) this, type(operators) ctx)
Definition at line 93 of file cmfd_jacobian_operator.F90.
References global::n_procs, and global::rank.
Referenced by init_J_operator().
subroutine cmfd_jacobian_operator::print_J_operator (jac)
Definition at line 328 of file cmfd_jacobian_operator.F90.
References ierr.
Referenced by build_jacobian_matrix().
Variable Documentation
integer cmfd_jacobian_operator::ierr
Definition at line 18 of file cmfd_jacobian_operator.F90.
Referenced by destroy_J_operator(), init_J_operator(), and print_J_operator().
integer cmfd_jacobian_operator::ng
Definition at line 17 of file cmfd_jacobian_operator.F90.
Referenced by init_J_operator().
integer cmfd_jacobian_operator::nx
Definition at line 14 of file cmfd_jacobian_operator.F90.
Referenced by init_J_operator().
integer cmfd_jacobian_operator::ny
Definition at line 15 of file cmfd_jacobian_operator.F90.
Referenced by init_J_operator().
integer cmfd_jacobian_operator::nz
Definition at line 16 of file cmfd_jacobian_operator.F90.
Referenced by init_J_operator().