CMFD: cmfd_execute Module Reference
cmfd_execute Module Reference
Routine for running the eigenvalue solve.
Functions/Subroutines
subroutine execute_cmfd ()
Detailed Description
Routine for running the eigenvalue solve.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine cmfd_execute::execute_cmfd ()
Definition at line 25 of file cmfd_execute.F90.
References cmfd_power_solver::cmfd_power_execute(), cmfd_slepc_solver::cmfd_slepc_execute(), cmfd_snes_solver::cmfd_snes_execute(), cmfd_data::set_up_cmfd(), and global::solver_type.
Referenced by main().