CMFD: cmfd_slepc_solver Module Reference
cmfd_slepc_solver Module Reference
Functions/Subroutines
subroutine cmfd_slepc_execute ()
subroutine init_data ()
subroutine init_solver ()
subroutine extract_results ()
subroutine finalize ()
Variables
type(loss_operator) loss
type(prod_operator) prod
integer ierr
real(8) keff
Function/Subroutine Documentation
subroutine cmfd_slepc_solver::cmfd_slepc_execute ()
Definition at line 31 of file cmfd_slepc_solver.F90.
References extract_results(), finalize(), ierr, init_data(), init_solver(), loss, and prod.
Referenced by cmfd_snes_solver::cmfd_snes_execute(), and cmfd_execute::execute_cmfd().
subroutine cmfd_slepc_solver::extract_results ()
Definition at line 126 of file cmfd_slepc_solver.F90.
References global::cmfd, ierr, keff, and loss.
Referenced by cmfd_slepc_execute().
subroutine cmfd_slepc_solver::finalize ()
Definition at line 182 of file cmfd_slepc_solver.F90.
References ierr, loss, and prod.
Referenced by cmfd_slepc_execute().
subroutine cmfd_slepc_solver::init_data ()
Definition at line 64 of file cmfd_slepc_solver.F90.
References ierr, cmfd_prod_operator::init_F_operator(), cmfd_loss_operator::init_M_operator(), loss, and prod.
Referenced by cmfd_slepc_execute().
subroutine cmfd_slepc_solver::init_solver ()
Definition at line 84 of file cmfd_slepc_solver.F90.
References ierr.
Referenced by cmfd_slepc_execute().
Variable Documentation
integer cmfd_slepc_solver::ierr
Definition at line 22 of file cmfd_slepc_solver.F90.
Referenced by cmfd_slepc_execute(), extract_results(), finalize(), init_data(), and init_solver().
real(8) cmfd_slepc_solver::keff
Definition at line 23 of file cmfd_slepc_solver.F90.
Referenced by extract_results().
type(loss_operator) cmfd_slepc_solver::loss
Definition at line 14 of file cmfd_slepc_solver.F90.
Referenced by cmfd_slepc_execute(), extract_results(), finalize(), and init_data().
type(prod_operator) cmfd_slepc_solver::prod
Definition at line 15 of file cmfd_slepc_solver.F90.
Referenced by cmfd_slepc_execute(), finalize(), and init_data().